#include 'totvs.ch'
#include "protheus.ch"

User function zTGet()
local oDlg1
local oSay1, oSay2, oSay3, oSay4
local oButton1
local aSize := MsAdvsize()

local cGet1 := Space(15)
local cGet2 := Space(20)
local cGet3 := Space(20)
local cGet4 := Space(20)

local oGet1, oGet2, oGet3, oGet4

oDlg1 := TDialog():New(aSize[7],aSize[1],aSize[6],aSize[5],'Aprendendo a usar o Tget',,,,, CLR_BLACK, CLR_WHITE,,, .T.)
oSay1 := TSay():New(10,10,{||'Digite seu nome'},oDlg1,,,,,,.T.,CLR_BLUE,CLR_WHITE,200,20)
oGet1 := TGet():New( 20,10,{|u|if(PCount()>0,cGet1:=u,cGet1)},oDlg1,60,10,"@!",,0,,,.F.,,.T.,,.F.,,.F.,.F.,,.F.,.F.,,cGet1,,,, )

oSay2 := TSay():New(10,100,{||'Digite o seu endereço'},oDlg1,,,,,,.T.,CLR_BLUE,CLR_WHITE,200,20)
oGet2 := TGet():New( 20,100,{|u|if(PCount()>0,cGet2:=u,cGet2)},oDlg1,300,10,"@!",,0,,,.F.,,.T.,,.F.,,.F.,.F.,,.F.,.F.,,cGet2,,,, )

oSay3 := TSay():New(10,440,{||'Número'},oDlg1,,,,,,.T.,CLR_BLUE,CLR_WHITE,200,20)
oGet3 := TGet():New( 20,440,{|u|if(PCount()>0,cGet3:=u,cGet3)},oDlg1,60,10,"@!",,0,,,.F.,,.T.,,.F.,,.F.,.F.,,.F.,.F.,,cGet3,,,, )

oSay4 := TSay():New(10,540,{||'Bairro'},oDlg1,,,,,,.T.,CLR_BLUE,CLR_WHITE,200,20)
oGet4 := TGet():New( 20,540,{|u|if(PCount()>0,cGet4:=u,cGet4)},oDlg1,200,10,"@!",,0,,,.F.,,.T.,,.F.,,.F.,.F.,,.F.,.F.,,cGet4,,,, )


oButton1 := TButton():New(50 , 10 , "Mostrar nome", oDlg1, {|| MsgInfo(cGet1,"Conteudo digitado")}, 60, 15, , ,.F., .T., .F.,, .F., , , .F.)

oDlg1:Activate(,,,)

return
