#include "totvs.ch"
#include "protheus.ch"


user function zTGroup()

local oDlg1

local oButton1
local oButton2
local oGroup1
local oGroup2

private oGet1
private oGet2
private oGet3
private oGet4

private cGet1 := Space(50)
private cGet2 := Space(50)
private cGet3 := Space(50)
private cGet4 := Space(50)


oDlg1 := TDialog():New(0, 0, 410, 410  , 'Cadastro de Usuário',,,,,CLR_BLACK, CLR_WHITE,,, .T.)

oGroup1 := TGroup():New(10,10,100,200,'Grupo 1',oDlg1,,,.T.)
oGet1 := TGet():New( 30,30,{|u|if(PCount()>0,cGet1:=u,cGet1)},oDlg1,100,10,"@!",,0,,,.F.,,.T.,,.F.,,.F.,.F.,,.F.,.F.,,cGet1,,,, )
oGet2 := TGet():New( 50,30,{|u|if(PCount()>0,cGet2:=u,cGet2)},oDlg1,100,10,"@!",,0,,,.F.,,.T.,,.F.,,.F.,.F.,,.F.,.F.,,cGet2,,,, )
oButton1 := TButton():New(80 , 30 , "Gerar gets", oDlg1, {|| EnviarGets()}, 60, 15, , ,.F., .T., .F.,, .F., , , .F.)


oGroup2 := TGroup():New(110,10,200,200,'Grupo 2',oDlg1,,,.T.)
oGet3 := TGet():New( 130,30,{|u|if(PCount()>0,cGet3:=u,cGet3)},oDlg1,100,10,"@!",,0,,,.F.,,.T.,,.F.,,.F.,.F.,,.T.,.F.,,cGet3,,,, )
oGet4 := TGet():New( 150,30,{|u|if(PCount()>0,cGet4:=u,cGet4)},oDlg1,100,10,"@!",,0,,,.F.,,.T.,,.F.,,.F.,.F.,,.T.,.F.,,cGet4,,,, )
oButton2 := TButton():New(180 , 30 , "Fechar", oDlg1, {|| oDlg1:end()}, 60, 15, , ,.F., .T., .F.,, .F., , , .F.)


oDlg1:ACTIVATE(,,,.T.)
return

Static Function EnviarGets()
    cGet3 := cGet1
    cGet4 := cGet2

    oGet3:Refresh()
    oGet4:Refresh()
Return
